name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd landing
          npm ci
          
      - name: Build
        run: |
          cd landing
          npm run build
          
      - name: Prepare root files
        run: |
          mkdir -p landing/out
          cp index.html landing/out/index.html
          cp -r .well-known landing/out/
          cp CNAME landing/out/
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing/out
          force_orphan: true

