name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd landing
          npm ci

      - name: Build
        run: |
          cd landing
          npm run build

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r landing/out deploy/landing
          cp index.html deploy/
          cp -r .well-known deploy/
          echo "sparkshift.app" > deploy/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: sparkshift.app

